name: Upload Control Tower configuration to S3
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME : "custom-control-tower-test-configuration-637423596514-us-east-1"
  AWS_REGION : "us-east-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # role-to-assume: "${{ vars.GH_ACT_IAM_ROLE }}"
          role-to-assume: "arn:aws:iam::637423596514:role/githubactions-webidentity"
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      # Archive the folder
      - name:  Create ZIP archive
        run: |
          zip -r custom-control-tower-configuration.zip .
      # Upload a file to AWS s3
      - name:  Copy ZIP archive to s3
        run: |
          aws s3 cp ./custom-control-tower-configuration.zip s3://${{ env.BUCKET_NAME }}/
